curl -o "README.md" "https://redsolution.id/project/README.md"
curl -o "tsconfig.json" "https://redsolution.id/project/tsconfig.json"
mkdir -p "pages"
curl -o "pages/index.tsx" "https://redsolution.id/project/pages/index.tsx"
curl -o "pages/bookmarks.tsx" "https://redsolution.id/project/pages/bookmarks.tsx"
curl -o "pages/_document.tsx" "https://redsolution.id/project/pages/_document.tsx"
curl -o "pages/admin.tsx" "https://redsolution.id/project/pages/admin.tsx"
mkdir -p "pages/artikel"
curl -o "pages/artikel/index.tsx" "https://redsolution.id/project/pages/artikel/index.tsx"
curl -o "pages/artikel/[slug].tsx" "https://redsolution.id/project/pages/artikel/[slug].tsx"
mkdir -p "pages/admin"
curl -o "pages/admin/index.tsx" "https://redsolution.id/project/pages/admin/index.tsx"
mkdir -p "pages/bookmarks"
curl -o "pages/bookmarks/index.tsx" "https://redsolution.id/project/pages/bookmarks/index.tsx"
mkdir -p "pages/lowongan-kerja"
curl -o "pages/lowongan-kerja/index.tsx" "https://redsolution.id/project/pages/lowongan-kerja/index.tsx"
curl -o "pages/lowongan-kerja/[slug].tsx" "https://redsolution.id/project/pages/lowongan-kerja/[slug].tsx"
curl -o "pages/_app.tsx" "https://redsolution.id/project/pages/_app.tsx"
curl -o "postcss.config.js" "https://redsolution.id/project/postcss.config.js"
mkdir -p "src/types"
curl -o "src/types/job.ts" "https://redsolution.id/project/src/types/job.ts"
mkdir -p "src/components"
curl -o "src/components/Breadcrumbs.tsx" "https://redsolution.id/project/src/components/Breadcrumbs.tsx"
mkdir -p "src/components/Layout"
curl -o "src/components/Layout/Header.tsx" "https://redsolution.id/project/src/components/Layout/Header.tsx"
curl -o "src/components/Layout/Footer.tsx" "https://redsolution.id/project/src/components/Layout/Footer.tsx"
mkdir -p "src/components/SEO"
curl -o "src/components/SEO/SchemaMarkup.tsx" "https://redsolution.id/project/src/components/SEO/SchemaMarkup.tsx"
mkdir -p "src/components/pages"
curl -o "src/components/pages/ArticleDetailPage.tsx" "https://redsolution.id/project/src/components/pages/ArticleDetailPage.tsx"
curl -o "src/components/pages/JobDetailPage.tsx" "https://redsolution.id/project/src/components/pages/JobDetailPage.tsx"
curl -o "src/components/pages/HomePage.tsx" "https://redsolution.id/project/src/components/pages/HomePage.tsx"
curl -o "src/components/pages/AdminPage.tsx" "https://redsolution.id/project/src/components/pages/AdminPage.tsx"
curl -o "src/components/pages/BookmarkPage.tsx" "https://redsolution.id/project/src/components/pages/BookmarkPage.tsx"
curl -o "src/components/pages/ArticlePage.tsx" "https://redsolution.id/project/src/components/pages/ArticlePage.tsx"
curl -o "src/components/pages/JobSearchPage.tsx" "https://redsolution.id/project/src/components/pages/JobSearchPage.tsx"
curl -o "src/components/JobSidebar.tsx" "https://redsolution.id/project/src/components/JobSidebar.tsx"
curl -o "src/components/SearchableSelect.tsx" "https://redsolution.id/project/src/components/SearchableSelect.tsx"
curl -o "src/components/JobCard.tsx" "https://redsolution.id/project/src/components/JobCard.tsx"
mkdir -p "src/utils"
curl -o "src/utils/urlUtils.ts" "https://redsolution.id/project/src/utils/urlUtils.ts"
curl -o "src/utils/schemaUtils.ts" "https://redsolution.id/project/src/utils/schemaUtils.ts"
mkdir -p "src/hooks"
curl -o "src/hooks/useInfiniteScroll.ts" "https://redsolution.id/project/src/hooks/useInfiniteScroll.ts"
mkdir -p "src/services"
curl -o "src/services/bookmarkService.ts" "https://redsolution.id/project/src/services/bookmarkService.ts"
curl -o "src/services/adminService.ts" "https://redsolution.id/project/src/services/adminService.ts"
curl -o "src/services/wpService.ts" "https://redsolution.id/project/src/services/wpService.ts"
curl -o "next.config.js" "https://redsolution.id/project/next.config.js"
curl -o "package.json" "https://redsolution.id/project/package.json"
curl -o ".gitignore" "https://redsolution.id/project/.gitignore"
curl -o ".eslintrc.json" "https://redsolution.id/project/.eslintrc.json"
curl -o "index.html" "https://redsolution.id/project/index.html"
curl -o "next-env.d.ts" "https://redsolution.id/project/next-env.d.ts"
mkdir -p ".bolt"
curl -o ".bolt/config.json" "https://redsolution.id/project/.bolt/config.json"
curl -o ".bolt/prompt" "https://redsolution.id/project/.bolt/prompt"
mkdir -p "styles"
curl -o "styles/globals.css" "https://redsolution.id/project/styles/globals.css"
mkdir -p ".next/cache/webpack/server-development"
curl -o ".next/cache/webpack/server-development/0.pack.gz" "https://redsolution.id/project/.next/cache/webpack/server-development/0.pack.gz"
curl -o ".next/cache/webpack/server-development/index.pack.gz" "https://redsolution.id/project/.next/cache/webpack/server-development/index.pack.gz"
curl -o ".next/cache/webpack/server-development/1.pack.gz" "https://redsolution.id/project/.next/cache/webpack/server-development/1.pack.gz"
curl -o ".next/cache/webpack/server-development/2.pack.gz" "https://redsolution.id/project/.next/cache/webpack/server-development/2.pack.gz"
curl -o ".next/cache/webpack/server-development/index.pack.gz.old" "https://redsolution.id/project/.next/cache/webpack/server-development/index.pack.gz.old"
mkdir -p ".next/cache/webpack/client-development"
curl -o ".next/cache/webpack/client-development/index.pack.gz.old" "https://redsolution.id/project/.next/cache/webpack/client-development/index.pack.gz.old"
curl -o ".next/cache/webpack/client-development/1.pack.gz" "https://redsolution.id/project/.next/cache/webpack/client-development/1.pack.gz"
curl -o ".next/cache/webpack/client-development/2.pack.gz" "https://redsolution.id/project/.next/cache/webpack/client-development/2.pack.gz"
curl -o ".next/cache/webpack/client-development/3.pack.gz" "https://redsolution.id/project/.next/cache/webpack/client-development/3.pack.gz"
curl -o ".next/cache/webpack/client-development/index.pack.gz" "https://redsolution.id/project/.next/cache/webpack/client-development/index.pack.gz"
curl -o ".next/cache/webpack/client-development/0.pack.gz" "https://redsolution.id/project/.next/cache/webpack/client-development/0.pack.gz"
mkdir -p ".next/static/development"
curl -o ".next/static/development/_buildManifest.js" "https://redsolution.id/project/.next/static/development/_buildManifest.js"
curl -o ".next/static/development/_ssgManifest.js" "https://redsolution.id/project/.next/static/development/_ssgManifest.js"
mkdir -p ".next/static/chunks"
curl -o ".next/static/chunks/webpack.js" "https://redsolution.id/project/.next/static/chunks/webpack.js"
curl -o ".next/static/chunks/main.js" "https://redsolution.id/project/.next/static/chunks/main.js"
mkdir -p ".next/static/chunks/pages"
curl -o ".next/static/chunks/pages/_error.js" "https://redsolution.id/project/.next/static/chunks/pages/_error.js"
curl -o ".next/static/chunks/pages/artikel.js" "https://redsolution.id/project/.next/static/chunks/pages/artikel.js"
curl -o ".next/static/chunks/pages/index.js" "https://redsolution.id/project/.next/static/chunks/pages/index.js"
curl -o ".next/static/chunks/pages/_app.js" "https://redsolution.id/project/.next/static/chunks/pages/_app.js"
mkdir -p ".next/static/chunks/pages/artikel"
curl -o ".next/static/chunks/pages/artikel/[slug].js" "https://redsolution.id/project/.next/static/chunks/pages/artikel/[slug].js"
curl -o ".next/static/chunks/pages/lowongan-kerja.js" "https://redsolution.id/project/.next/static/chunks/pages/lowongan-kerja.js"
curl -o ".next/static/chunks/_error.js" "https://redsolution.id/project/.next/static/chunks/_error.js"
curl -o ".next/static/chunks/polyfills.js" "https://redsolution.id/project/.next/static/chunks/polyfills.js"
curl -o ".next/static/chunks/react-refresh.js" "https://redsolution.id/project/.next/static/chunks/react-refresh.js"
curl -o ".next/static/chunks/src_services_wpService_ts.js" "https://redsolution.id/project/.next/static/chunks/src_services_wpService_ts.js"
mkdir -p ".next/static/webpack"
curl -o ".next/static/webpack/webpack.6d71ea142bde9062.hot-update.js" "https://redsolution.id/project/.next/static/webpack/webpack.6d71ea142bde9062.hot-update.js"
curl -o ".next/static/webpack/6d71ea142bde9062.webpack.hot-update.json" "https://redsolution.id/project/.next/static/webpack/6d71ea142bde9062.webpack.hot-update.json"
curl -o ".next/static/webpack/a9941427f22c5c7d.webpack.hot-update.json" "https://redsolution.id/project/.next/static/webpack/a9941427f22c5c7d.webpack.hot-update.json"
curl -o ".next/static/webpack/633457081244afec._.hot-update.json" "https://redsolution.id/project/.next/static/webpack/633457081244afec._.hot-update.json"
curl -o ".next/static/webpack/webpack.3308f6c3c47a1853.hot-update.js" "https://redsolution.id/project/.next/static/webpack/webpack.3308f6c3c47a1853.hot-update.js"
curl -o ".next/static/webpack/3308f6c3c47a1853.webpack.hot-update.json" "https://redsolution.id/project/.next/static/webpack/3308f6c3c47a1853.webpack.hot-update.json"
curl -o ".next/static/webpack/webpack.a9941427f22c5c7d.hot-update.js" "https://redsolution.id/project/.next/static/webpack/webpack.a9941427f22c5c7d.hot-update.js"
mkdir -p ".next"
curl -o ".next/build-manifest.json" "https://redsolution.id/project/.next/build-manifest.json"
curl -o ".next/trace" "https://redsolution.id/project/.next/trace"
mkdir -p ".next/server"
curl -o ".next/server/interception-route-rewrite-manifest.js" "https://redsolution.id/project/.next/server/interception-route-rewrite-manifest.js"
curl -o ".next/server/middleware-react-loadable-manifest.js" "https://redsolution.id/project/.next/server/middleware-react-loadable-manifest.js"
curl -o ".next/server/next-font-manifest.js" "https://redsolution.id/project/.next/server/next-font-manifest.js"
mkdir -p ".next/server/pages"
curl -o ".next/server/pages/_error.js" "https://redsolution.id/project/.next/server/pages/_error.js"
curl -o ".next/server/pages/index.js" "https://redsolution.id/project/.next/server/pages/index.js"
curl -o ".next/server/pages/_document.js" "https://redsolution.id/project/.next/server/pages/_document.js"
curl -o ".next/server/pages/artikel.js" "https://redsolution.id/project/.next/server/pages/artikel.js"
curl -o ".next/server/pages/lowongan-kerja.js" "https://redsolution.id/project/.next/server/pages/lowongan-kerja.js"
curl -o ".next/server/pages/_app.js" "https://redsolution.id/project/.next/server/pages/_app.js"
mkdir -p ".next/server/pages/artikel"
curl -o ".next/server/pages/artikel/[slug].js" "https://redsolution.id/project/.next/server/pages/artikel/[slug].js"
curl -o ".next/server/next-font-manifest.json" "https://redsolution.id/project/.next/server/next-font-manifest.json"
curl -o ".next/server/_error.js" "https://redsolution.id/project/.next/server/_error.js"
curl -o ".next/server/src_services_wpService_ts.js" "https://redsolution.id/project/.next/server/src_services_wpService_ts.js"
curl -o ".next/server/webpack-runtime.js" "https://redsolution.id/project/.next/server/webpack-runtime.js"
mkdir -p ".next/server/vendor-chunks"
curl -o ".next/server/vendor-chunks/@swc.js" "https://redsolution.id/project/.next/server/vendor-chunks/@swc.js"
curl -o ".next/server/vendor-chunks/next.js" "https://redsolution.id/project/.next/server/vendor-chunks/next.js"
curl -o ".next/server/vendor-chunks/lucide-react.js" "https://redsolution.id/project/.next/server/vendor-chunks/lucide-react.js"
curl -o ".next/server/middleware-manifest.json" "https://redsolution.id/project/.next/server/middleware-manifest.json"
curl -o ".next/server/pages-manifest.json" "https://redsolution.id/project/.next/server/pages-manifest.json"
curl -o ".next/server/middleware-build-manifest.js" "https://redsolution.id/project/.next/server/middleware-build-manifest.js"
curl -o ".next/package.json" "https://redsolution.id/project/.next/package.json"
curl -o ".next/react-loadable-manifest.json" "https://redsolution.id/project/.next/react-loadable-manifest.json"
curl -o "tailwind.config.js" "https://redsolution.id/project/tailwind.config.js"
curl -o "package-lock.json" "https://redsolution.id/project/package-lock.json"
curl -o "mapping2.php" "https://redsolution.id/project/mapping2.php"
